### ISSUE TITLE
Still receiving a post-2.0 error

### ISSUE THREAD

**Issue by GHExplorer** [clojure-numerics/expresso#14]
Hi,

Still can't resolve this.  I can use the most recent post 2.0 expresso by using the Jar with other languages.  But Clojure projects return an error.

:dependencies [[org.clojure/clojure "1.6.0"]
                 [expresso "0.2.1-SNAPSHOT"]
                  ]

that produces this:

Compiling espressodemo.core
java.lang.NoSuchMethodError: clojure.core.logic.LVar.<init>(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V, compiling:(core.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
	at clojure.lang.Compiler.compile1(Compiler.java:7226)
	at clojure.lang.Compiler.compile1(Compiler.java:7216)
	at clojure.lang.Compiler.compile(Compiler.java:7292)
	at clojure.lang.RT.compile(RT.java:398)
	at clojure.lang.RT.load(RT.java:438)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$compile$fn__5071.invoke(core.clj:5652)
	at clojure.core$compile.invoke(core.clj:5651)
	at user$eval9$fn__16.invoke(form-init6777542118122910961.clj:1)
	at user$eval9.invoke(form-init6777542118122910961.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

**Comment by mschuene** [comment]
I can't reproduce this
I created a new project
(defproject exprtest "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [expresso "0.2.1-SNAPSHOT"]])


with core.clj
(ns exprtest.core
  (:use [numeric.expresso.core :as exp]))

(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))


(exp/ex (+ x y z))


everything works as expected, I get no errors

**Comment by GHExplorer** [comment]
Good.  Got it.

I had

(defproject espressodemo "0.2.1-SNAPSHOT"
  :description "Express Demo"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [expresso "0.2.1-SNAPSHOT"]
                  ]
  :javac-options ["-target" "1.6" "-source" "1.6" "-Xlint:-options"]
  :aot [espressodemo.core]
  :main espressodemo.core)


, and took out the aot key, and changed it to the following, based on your project file:


(defproject espressodemo "0.2.1-SNAPSHOT"
  :description "Express Demo"
:dependencies [[org.clojure/clojure "1.6.0"]
[expresso "0.2.1-SNAPSHOT"]])



, aaaaand, back in business.  Thanks, chief.
